### ISSUE TITLE
Github: Inform about new issues from non-collaboratives

### ISSUE THREAD

**Issue by TomlDev** [edulution-io/edulution-ui#964]
You can’t do this purely with GitHub’s built-in notifications (which don’t let you filter by “is contributor vs. is team-member”), but it’s trivial to wire up a tiny GitHub Action that:

1. Listens for `issues.opened`
2. Checks “is the opener a collaborator / member of our org or team?”
3. If **not**, sends you an email (or Slack/Webhook, whatever you like).

---

## 1) Create a workflow

Add a file in your repo at
`.github/workflows/notify-external-issues.yml`:

```yaml
name: “Notify me of external issues”

on:
  issues:
    types: [opened]

jobs:
  notify-external:
    runs-on: ubuntu-latest
    steps:

      # 1) figure out the opener’s role in this repo
      - name: check collaborator permission
        id: perm
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const login = context.payload.issue.user.login;
            // getCollaboratorPermissionLevel will 404 if not a collaborator
            let permLevel = 'none';
            try {
              const res = await github.rest.repos.getCollaboratorPermissionLevel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                username: login,
              });
              permLevel = res.data.permission;  // 'admin' / 'write' / 'read'
            } catch (err) { /* not a collaborator */ }
            core.setOutput('permission', permLevel);

      # 2) if they’re not at least a read-collaborator, send you an email
      - name: send SMTP email
        if: steps.perm.outputs.permission == 'none'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "[🚨 External Issue] #${{ github.event.issue.number }} opened"
          body: |
            User:    ${{ github.event.issue.user.login }}
            Repo:    ${{ github.repository }}
            Issue:   #${{ github.event.issue.number }} – ${{ github.event.issue.title }}
            URL:     ${{ github.event.issue.html_url }}

            ${{
              github.event.issue.body
                ? github.event.issue.body.substring(0, 200) + '…'
                : '(no description)'
            }}
          to: your.email@yourdomain.com
          from: noreply@yourdomain.com
```

### What this does

- **`actions/github-script`** checks the opener’s permission level in your repo.
- If it comes back as `none` (i.e. not a collaborator/team-member), the next step fires.
- **`dawidd6/action-send-mail`** uses a real SMTP server (Gmail, your company, etc.) to email you the issue details.

---

## 2) Set up your secrets

In your repo Settings → Secrets → Actions, add:

- `SMTP_USER` & `SMTP_PASS` (SMTP login for your mail server)
- You’ll already have `GITHUB_TOKEN` by default.
